@baseUrl = http://demo1.local
@token = test

### Get All Buttons
GET {{baseUrl}}/buttons
Authorization: Bearer {{token}}

###

### Create or Update Buttons
POST {{baseUrl}}/buttons
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "buttons": [
    {
      "id": 1,
      "name": "WiFi Password",
      "category": "Passwords",
      "action": "Type",
      "command": "password123",
      "notes": "Updated WiFi password for guests"
    },
    {
      "id": 3,
      "name": "Turn On LEDs",
      "category": "LED Controls",
      "action": "Run",
      "command": "led on",
      "notes": "Turns on all LED lights"
    }
  ]
}

###

### update a button
POST {{baseUrl}}/buttons
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "buttons": [
    {
      "id": 1,
      "notes": "Updated WiFi password for guests2"
    }
  ]
}

###
http://demo1.local/buttons?id=1737767037313 

### Delete a Button
DELETE {{baseUrl}}/buttons?id=1
Authorization: Bearer {{token}}
Content-Type: application/json

###

