name: PlatformIO Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.get_tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Tag Name
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Debug GITHUB_ENV
        run: cat $GITHUB_ENV

      - name: Debug Tag Name
        env:
          TAG: ${{ env.tag }}
        run: |
          echo "Tag name: $TAG"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up PlatformIO
        run: |
          python3 -m pip install -U pip
          pip install platformio

      - name: Build firmware
        run: |
          pio run --environment esp32-s3-devkitc-1

      - name: Debug list firmware directory
        run: ls -R .pio/build/esp32-s3-devkitc-1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .pio/build/esp32-s3-devkitc-1/device.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
