@baseUrl = http://demo.local

### Get settings
GET {{baseUrl}}/settings/get

###

### Set settings
POST {{baseUrl}}/settings/save
Content-Type: application/json

{
  "ssid": "demo",
  "password": "example"
}

###