@baseUrl = http://demo.local
@token = test

### Get actions
GET {{baseUrl}}/actions/get
Authorization: Bearer {{token}}

###

### Reboot
POST {{baseUrl}}/actions/set
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "action": "reboot"
}

###

### Tft
POST {{baseUrl}}/actions/set
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "action": "tft",
  "message": "Hello1!"
}

###

### Led
POST {{baseUrl}}/actions/set
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "action": "led",
  "message": "Red"
}

###